apiVersion: v1
kind: Service
metadata:
  labels:
    app: testspring
  name: testspring
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testspring
  type: LoadBalancer
  #  type: NodePort # this is required for docker-for-desktop
