apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret
  labels:
    app: secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      name: private-reg
      labels:
        app: secret
    spec:
      containers:
      - name: secret-cont
        image: ramgop/secret
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: regcred1
