apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret
  name: secret
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: secret
  type: LoadBalancer
