apiVersion: v1
kind: Service
metadata:
  labels:
    app: testspringconfigmap
  name: testspringconfigmap
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testspringconfigmap
  type: LoadBalancer
